### ISSUE TITLE
Toks not working on Windows 10 64-bit

### ISSUE THREAD

**Issue by ZenithDK** [thomasthorsen/toks#3]
When I try to look up a symbol using toks (after indexing the code) I get this error in the shell:
```
Traceback (most recent call last):
 File "C:\Users\lbig\AppData\Roaming\Sublime Text 3\Packages\Toks\SublimeToks.py", line 269, in on_highlighted
   view = sublime.active_window().find_open_file(match.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```
In spite of this, it pops up the result list, and when I then press the found result, I get this:
```
Traceback (most recent call last):
 File "C:\Users\lbig\AppData\Roaming\Sublime Text 3\Packages\Toks\SublimeToks.py", line 269, in on_highlighted
   view = sublime.active_window().find_open_file(match.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
 File "C:\Users\lbig\AppData\Roaming\Sublime Text 3\Packages\Toks\SublimeToks.py", line 259, in on_select
   self.navigate_jump(self.pre_lookup_position, location)
 File "C:\Users\lbig\AppData\Roaming\Sublime Text 3\Packages\Toks\SublimeToks.py", line 249, in navigate_jump
   if self.is_history_empty() or not self.is_same_location(self.back_lines[0], source):
 File "C:\Users\lbig\AppData\Roaming\Sublime Text 3\Packages\Toks\SublimeToks.py", line 212, in is_same_location
   if match1.group(1) == match2.group(1) and \
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by ZenithDK** [comment]
The problem seems to be that on Windows you get a path such as "C:\..."

I added this debug line:
```
sublime.error_message("SublimeToks: location {} - match: {}".format(location, match))
```

And the debug was this:
```
error: SublimeToks: location C:\Users\lbig\workspace\DuplexBT\vmkit\src\secom\bt_devMan\bt_devMan.c:605:13 - match: None
```

Changing the regexp to:
(.+):\d+:\d+
fixes the problem. This needs to be done in line 268, and the regexps in line 210 and 211 need to be modified as well.

**Comment by ZenithDK** [comment]
Created for the wrong project, it's related to SublimeToks, not toks itself.
